---
title: "Modelling"
author: "Eric Zhu, Brian Diep, Tanvir Hyder, Ashley Zhang, Kristin Huang"
date: "09/19/2021"
output:
  pdf_document: 
    toc: yes
    toc_depth: 3
    extra_dependencies: ["float"]
header-includes:
- \usepackage{fancyhdr}
- \usepackage[T1]{fontenc}
- \usepackage{lmodern}
- \usepackage{bm}
- \usepackage[ruled,vlined]{algorithm2e}
- \usepackage{setspace}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \usepackage{float}
- \floatplacement{figure}{H}
- \fancyhead[LO,LE]{Eric Zhu, Brian Diep, Tanvir Hyder, Ashley Zhang, Kristin Huang}
---

```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(brms)
library(lme4)

predictors_df <- read_csv("predictors_dataframe.csv")
predictors_df <- predictors_df %>%
  select(-c(1:3, 6))
names(predictors_df) <- c('home_ownership', 'income_bracket', 'is_immigrant',
                          'education', 'language', 'votechoice', 'age_bracket',
                          'Province')

```

```{r}
model <- nnet::multinom(votechoice ~ Province + education + income_bracket + home_ownership + language + is_immigrant + age_bracket, data = predictors_df, maxit=500)
broom::tidy(model)
#summary(model)
```

```{r}
library(caret)

predictors_df$votechoice <- as.factor(predictors_df$votechoice)
poststrat_data <- read_csv('../poststrat.csv')
poststrat_data <- poststrat_data %>%
  select(-c(1))
province_data <- read_csv('../wrangled_data/Riding_by_province.csv')
province_data <- province_data %>%
  arrange(Riding) %>%
  select(-c(1:2))
province_data$custom_code <- 1:338
Riding <- unique(poststrat_data$Riding)
custom_code <- 1:338
custom_code <- cbind(Riding, custom_code)

poststrat_data <- inner_join(poststrat_data, custom_code, by=c("Riding"))
poststrat_data <- inner_join(poststrat_data, province_data, by=c("custom_code"))
num_ridings <- length(unique(poststrat_data$custom_code))
```


```{r}
predicted_vote <- predict(model, type="class", newdata=poststrat_data)
pred <- data.frame(predicted_vote)
poststrat_data <- cbind(poststrat_data, predicted_vote)
```

```{r}

poststrat_data_j <- poststrat_data %>%
  select(c(Riding, custom_code, prop, predicted_vote)) %>% 
  group_by(Riding, custom_code, predicted_vote) %>%
  summarise_all(sum)  %>% 
  ungroup() %>% 
  mutate(custom_code = as.numeric(custom_code)) %>% 
  group_by(custom_code) %>% 
  top_n(n=1, prop) %>% 
  ungroup() %>%
  slice(-c(70, 71, 72))


```
# Check dataframe 
```{r}
predicted_summaries <- poststrat_data_j %>% group_by(predicted_vote) %>% dplyr::summarise(n =n())

```

# Convert to submission format

```{r}
submission_df <- poststrat_data_j %>% left_join(province_data, by = "custom_code") %>% ungroup() %>%select(c(predicted_vote, "Geo Code")) 
submission_df <- submission_df %>% mutate(forecast_winner = case_when(
  predicted_vote == 1 ~ 'LPC',
  predicted_vote == 2 ~ 'CPC',
  predicted_vote == 3 ~ 'NDP',
  predicted_vote == 4 ~ 'BQ',
  predicted_vote == 5 ~ 'GPC',
  predicted_vote == 6 ~ 'PPC',
)) %>% 
  select(-c(predicted_vote)) %>%
  rename(riding_code = "Geo Code")
write.csv(submission_df,  "can_election_21_forecast.csv")
```
