---
title: "post strat"
output: pdf_document
---

```{r, message=FALSE}
library(haven)
library(tidyverse)

# Read federal riding census data
riding <- read_csv('C:/Users/ericz/Desktop/ML compeititons/forecasting-2021-canada-election/data/riding_data/98-401-X2016045_English_CSV_data.csv')

# Filter off provincial/national aggregates
riding <- riding %>%
  subset(GEO_LEVEL == 2)

# Get human-readable names for columns
prompt <- riding[1:2247,9]

riding_male <- riding %>%
  select(
    GEO_NAME,
    colnames(riding)[10],
    colnames(riding)[13]
    )

riding_female <- riding %>%
  select(
    GEO_NAME,
    colnames(riding)[10],
    colnames(riding)[14]
  )

riding_total <- riding %>%
  select(
    GEO_NAME,
    colnames(riding)[10],
    colnames(riding)[12]
  )

names(riding_male)[1] <- 'Riding'
names(riding_male)[2] <- 'Code'
names(riding_male)[3] <- 'Val'

names(riding_female)[1] <- 'Riding'
names(riding_female)[2] <- 'Code'
names(riding_female)[3] <- 'Val'

names(riding_total)[1] <- 'Riding'
names(riding_total)[2] <- 'Code'
names(riding_total)[3] <- 'Val'


riding_total <- riding_total %>%
  pivot_wider(names_from= Code, values_from = Val)

riding_male <- riding_male %>%
  pivot_wider(names_from = Code, values_from = Val)

riding_female <- riding_female %>%
  pivot_wider(names_from = Code, values_from = Val)

riding_male$sex <- c('male')
riding_female$sex <- c('female')

age_cols <- 9:33
income_cols <- 760:780
home_ownership_cols <- 1618:1620
language_cols <- 106:109
education_cols <- 1685:1698
#ethnicity_cols <- 1325:1337
home_cols <- 1676
immigrants_cols <- 1141:1142
sex <- 2249
employment_cols <- 1867:1869

prompt_subset <- prompt[c(age_cols,
         income_cols,
         home_ownership_cols,
         language_cols,
         education_cols,
         home_cols,
         immigrants_cols,
         sex,
         employment_cols),]


riding_data <- rbind(riding_male, riding_female)

riding_full_data <- riding_data %>%
  select(1,
         age_cols,
         income_cols,
         home_ownership_cols,
         language_cols,
         education_cols,
         home_cols,
         immigrants_cols,
         sex,
         employment_cols)

riding_income_data <- riding_total %>%
  select(1, income_cols) %>%
  select(-c('759', '775'))

riding_education_data <- riding_data %>%
  select(1, education_cols, sex)

riding_employment_data <- riding_data %>%
  select(1, employment_cols, sex)

riding_immigration_data <- riding_data %>%
  select(1, 1142, 1143, sex)

names(riding_income_data) <- c("Riding", deframe(prompt[760:774,]), 
                               deframe(prompt[776:779,]))
riding_income_data <- riding_income_data %>%
  mutate(
  "0-30k" = rowSums(.[2:7]),
  "30-60k" = rowSums(.[8:12]),
  "60-90k" = rowSums(.[13:15]),
  "90-150k" = rowSums(.[16:18]),
  "150-200k" = rowSums(.[19]),
  "200k+" = rowSums(.[20])
  ) %>% 
  select(-c(2:20))

names(riding_education_data) <- c("Riding", deframe(prompt[education_cols,]), "Sex")
riding_education_data[, c(2:15)] <- sapply(riding_education_data[, c(2:15)], as.numeric)
riding_education_data <- riding_education_data %>%
  mutate(
    "No degree/diploma" = rowSums(.[2]),
    "High school" = rowSums(.[3]),
    "College/Trades" = rowSums(.[c(4:9)]),
    "Bachelors" = rowSums(.[10:11]),
    "Postgrad" = rowSums(.[12:15])
  ) %>%
  select(-c(2:15))

names(riding_employment_data) <- c("Riding", deframe(prompt[employment_cols,]), "Sex")
riding_employment_data[, c(2:4)] <- sapply(riding_employment_data[, c(2:4)], as.numeric)

names(riding_immigration_data) <- c("Riding", "Non-immigrant", "Immigrant", "Sex")
riding_immigration_data[, c(2:3)] <- sapply(riding_immigration_data[, c(2:3)], as.numeric)

immigration_prop <- riding_immigration_data %>% 
  pivot_longer(cols=2:3, names_to="is_immigrant", values_to="n") %>%
  group_by(Riding, Sex) %>%
  mutate(freq = n / sum(n))

employment_prop <- riding_employment_data %>%
  pivot_longer(cols=2:4, names_to="employment_status", values_to="n") %>%
  group_by(Riding, Sex) %>%
  mutate(freq = n / sum(n))

education_prop <- riding_education_data %>%
  pivot_longer(cols=3:7, names_to="education", values_to="n") %>%
  group_by(Riding, Sex) %>%
  mutate(freq = n / sum(n))

income_prop <- riding_income_data %>%
  pivot_longer(cols=2:7, names_to="income_bracket", values_to="n") %>%
  group_by(Riding) %>%
  mutate(freq = n / sum(n))

x <- merge(immigration_prop, employment_prop, by=c("Riding", "Sex")) %>%
  rename(f1 = freq.x,
         f2 = freq.y) %>%
  select(-c(4, 7))

y <- merge(x, education_prop, by=c("Riding", "Sex")) %>%
  rename(
    f3 = freq
  ) %>%
  select(-c(8))

z <- merge(y, income_prop, by="Riding") %>%
  rename(
    f4 = freq
  ) %>%
  select(-c(10))

z <- z %>%
  mutate(prop = f1 * f2 * f3 * f4) %>%
  select(-c(f1, f2, f3, f4))

ages <- read_csv('Ages.csv')
ages$Sex <- tolower(ages$Sex)
#ethnicity <- read_csv('Ethnicity.csv')
#ethnicity$Sex <- tolower(ethnicity$Sex)
home <- read_csv('Homeownership.csv')
language <- read_csv('Language (3).csv')
language$Sex <- tolower(language$Sex)
```


```{r}
x <- merge(z, ages, by=c("Riding", "Sex")) %>%
  rename(
    f5 = freq
  ) %>%
  select(-c(8, 10)) %>%
  mutate(prop = prop * f5) %>%
  select(-c(f5))


#y <- merge(x, ethnicity, by=c("Riding", "Sex")) %>%
  #rename(
    #f6 = freq
  #) %>%
  #select(-c(9, 11)) %>%
  #mutate(prop = prop * f6) %>%
  #select(-c(f6))

z <- merge(x, home, by="Riding") %>%
  rename(
    f7 = freq
  ) %>%
  select(-c(9, 11)) %>%
  mutate(prop = prop * f7) %>%
  select(-c(f7))

x <- merge(z, language, by="Riding") %>%
  rename(
    f8 = freq
  ) %>%
  select(-c(10, 12)) %>%
  mutate(prop = prop * f8) %>%
  select(-c(f8))
```


